# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x15lamport_logical_clock\"Q\n\x12MsgDeliveryRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x03\x12\r\n\x05\x63lock\x18\x04 \x01(\x03\"S\n\x10MsgDeliveryReply\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x03\x12\r\n\x05\x63lock\x18\x04 \x01(\x03\x32q\n\nBankSystem\x12\x63\n\x0bMsgDelivery\x12).lamport_logical_clock.MsgDeliveryRequest\x1a\'.lamport_logical_clock.MsgDeliveryReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGDELIVERYREQUEST._serialized_start=37
  _MSGDELIVERYREQUEST._serialized_end=118
  _MSGDELIVERYREPLY._serialized_start=120
  _MSGDELIVERYREPLY._serialized_end=203
  _BANKSYSTEM._serialized_start=205
  _BANKSYSTEM._serialized_end=318
# @@protoc_insertion_point(module_scope)
