# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x05proj1\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x04\x42\x61nk\x12\x34\n\x08SayHello\x12\x13.proj1.HelloRequest\x1a\x11.proj1.HelloReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:proj1.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:proj1.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_BANK = DESCRIPTOR.services_by_name['Bank']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=21
  _HELLOREQUEST._serialized_end=49
  _HELLOREPLY._serialized_start=51
  _HELLOREPLY._serialized_end=80
  _BANK._serialized_start=82
  _BANK._serialized_end=142
# @@protoc_insertion_point(module_scope)
